### ISSUE TITLE
add tree catalogue

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/dt-react-component#193]
![image](https://user-images.githubusercontent.com/34759874/184780830-49288a76-66df-4e92-82c0-b2ca8306eea8.png)
![image](https://user-images.githubusercontent.com/34759874/184780856-401dcd7d-a8f9-4b59-be64-f45461d2dda3.png)
![image](https://user-images.githubusercontent.com/34759874/184780904-49698bb8-1290-4a63-8cc1-6ef339ec71ff.png)
![image](https://user-images.githubusercontent.com/34759874/184780920-d35991e2-d361-4c31-9a93-e239eff69724.png)
![image](https://user-images.githubusercontent.com/34759874/184780947-3036c959-c359-4538-a8ae-71f04a52e63f.png)

**Comment by mumiao** [comment]
放在下个版本 @OnlyFlyer

**Comment by mumiao** [comment]
@OnlyFlyer dilu   这个有计划么。在哪个时间点去做，我记得之前 @liuxy0551 那边沟通是已经 `in-progress` 了

**Comment by OnlyFlyer** [comment]
进行中，进度大概60%，最近迭代较忙搁置了，近期会启动，大概月底能够提 PR

**Comment by mumiao** [comment]
> 进行中，进度大概60%，最近迭代较忙搁置了，近期会启动，大概月底能够提 PR

好的，根据你的节奏来。我确定了一个大概的ddl就行，辛苦拉😄

**Comment by mumiao** [comment]
done
