### ISSUE TITLE
MxGraph 组件样式覆盖问题

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-react-component#198]
MxGraph 组件内部样式类名应当带有 dt-react-component 自己的类名前缀

**Comment by HaydenOrz** [comment]
这几个 import 没有加 `.scss` 文件扩展名，与其他引入不同，是否同意一下。
![image](https://user-images.githubusercontent.com/58289241/187587517-d2d32a28-03e9-40eb-9911-ce61ca2809bf.png)

**Comment by liuxy0551** [comment]
> 这几个 import 没有加 `.scss` 文件扩展名，与其他引入不同，是否统一一下。 ![image](https://user-images.githubusercontent.com/58289241/187587517-d2d32a28-03e9-40eb-9911-ce61ca2809bf.png)

![image](https://user-images.githubusercontent.com/34759874/187851396-68489152-6cd9-450b-9569-e8de295d8d0f.png)
beta_3.0.0 分支已经做了处理，即将发布，2.x 就暂不处理了。

**Comment by liuxy0551** [comment]
> 这几个 import 没有加 `.scss` 文件扩展名，与其他引入不同，是否统一一下。 ![image](https://user-images.githubusercontent.com/58289241/187587517-d2d32a28-03e9-40eb-9911-ce61ca2809bf.png)

![image](https://user-images.githubusercontent.com/34759874/187851396-68489152-6cd9-450b-9569-e8de295d8d0f.png)
beta_3.0.0 分支已经做了处理，即将发布，2.x 就暂不处理了。

**Comment by liuxy0551** [comment]
#199
