### ISSUE TITLE
handsontable @babel/polyfill

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/dt-react-component#201]
低版本的 handsontable 引用了 @babel/polyfill，在 Monorepo 架构下会有幽灵依赖的问题，导致单测报错。调研下升级 handsontable。
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/34759874/188113665-91550a34-642f-4295-9df8-cbe921b10f4d.png">

**Comment by mumiao** [comment]
**handsontable**最新版本依赖了 "@babel/polyfill": "^7.8.3", 并没有**deprecated**掉这个**@babel/polyfill**,  Monorepo Pnpm 架构下，只会有**packages**下面的**dependencies**即
运行时依赖，因此本地跑**Unit Cases**, 缺失了 **@babel/polyfill**的包，不是幽灵依赖的问题

**Comment by mumiao** [comment]
@babel编译的包，不打算作为基础包的运行时依赖，解法我再权衡一下

**Comment by liuxy0551** [comment]
babel/polyfill@7 不再维护，所以考虑升级 handsontable，高版本的 handsontable 不再依赖 babel/polyfill@7

**Comment by mumiao** [comment]
https://github.com/handsontable/handsontable/blob/12.1.2/package.json **handsontable**最高版本还是依赖了哦

> babel/polyfill@7 不再维护，所以考虑升级 handsontable，高版本的 handsontable 不再依赖 babel/polyfill@7

https://github.com/handsontable/handsontable/blob/12.1.2/package.json **handsontable**最高版本还是依赖了哦

**Comment by mumiao** [comment]
> babel/polyfill@7 不再维护，所以考虑升级 handsontable，高版本的 handsontable 不再依赖 babel/polyfill@7

"@handsontable/react 这个包把polyfill废弃了，单元测试报错的是**handsontable**包

**Comment by mumiao** [comment]
@liuxy0551 break changing 放在beta3里面了
