### ISSUE TITLE
fix ModalWithForm footer text

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/dt-react-component#209]
目前使用 ModalWithForm 组件的 footer 文本都是英文

![image](https://user-images.githubusercontent.com/38368040/190310130-8f3ed5d0-88ec-4d37-87c3-3a2cc2949553.png)

**Comment by mumiao** [comment]
@LuckyFBB 这个小问题，提个pr上来

**Comment by LuckyFBB** [comment]
![image](https://user-images.githubusercontent.com/38368040/191706641-1f3ac50c-23ec-4a6f-9b54-9dc29a5da43c.png)
这个我看 @liuxy0551 已经修了
