### ISSUE TITLE
BlockHeader 组件

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/dt-react-component#227]
![image](https://user-images.githubusercontent.com/38368040/195487360-ecd3104c-4c3d-4e98-9529-47c7d2c1790e.png)

1. 使用 BlockHeader 实现简洁版无背景标题时，默认前面会有 padding-left 12，margin-left 8，这是不被期望的

2. 针对于 afterTitle 来说，是否能够支持一个 tooltip 参数，直接使用<Tooltip> 问号的形式。由于目前使用较多的是 问号提示的tooltip，否则每次都需要自动引入一个 <Tooltip> 组件

**Comment by mumiao** [comment]
done
