### ISSUE TITLE
Antd Tag 组件扩展

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/dt-react-component#229]
![image](https://user-images.githubusercontent.com/34759874/195495187-779bfe8f-97c3-4533-b5af-10ca3f5f3dcc.png)

新增一个组件，类似 Antd Tag 组件，支持传入颜色；  
由于设计改变了原来的样式，可以用来替换 RC 的 Circle 组件  
![image](https://user-images.githubusercontent.com/34759874/195495343-e17c3afe-4a1c-4e62-9172-4e591efbb280.png)

**Comment by mumiao** [comment]
done
