### ISSUE TITLE
ContextMenu - 新版组件问题

### ISSUE THREAD

**Issue by OnlyFlyer** [DTStack/dt-react-component#247]
### 建议
1. 建议给 data 赋一个默认值
2. 当 data 传递空数组时，右键 item 会有一个白边

<img width="385" alt="image" src="https://user-images.githubusercontent.com/19942622/200995196-8056b6d9-b227-4f1c-a9fe-ea4ab3f936a5.png">

### 解决方案

![image](https://user-images.githubusercontent.com/19942622/200995370-79d02d29-9f07-436f-8a9a-4c80d806d9fb.png)

### 验证地址

应用：dt-insight-studio
分支：batch/feat_5.3.x_UI5.0_dilu
路由：/offline/task

### 
![image](https://user-images.githubusercontent.com/22880945/201014498-71a63e33-2dfe-46ed-a6f0-452fbb462ed2.png)

**Comment by mumiao** [comment]
done
