### ISSUE TITLE
分类标题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/dt-react-component#250]
![image](https://user-images.githubusercontent.com/92357451/202076753-f176afae-d8ae-44d4-a890-2274a01a5473.png)
这个模块可以分为两个一级分类：大标题和小标题
然后再从大标题这里分出两类：带灰色背景（默认、标题+icon、带文字说明、简洁版）和不带灰色背景（默认、标题+icon、带文字说明、简洁版）
再从小标题分出两类：带灰色背景（默认、标题+icon、简洁版）和不带灰色背景（默认、标题+icon、简洁版）
现在这样的示例方式有点乱，不方便去选择用哪种

**Comment by LuckyFBB** [comment]
> ![image](https://user-images.githubusercontent.com/92357451/202076753-f176afae-d8ae-44d4-a890-2274a01a5473.png) 这个模块可以分为两个一级分类：大标题和小标题 然后再从大标题这里分出两类：带灰色背景（默认、标题+icon、带文字说明、简洁版）和不带灰色背景（默认、标题+icon、带文字说明、简洁版） 再从小标题分出两类：带灰色背景（默认、标题+icon、简洁版）和不带灰色背景（默认、标题+icon、简洁版） 现在这样的示例方式有点乱，不方便去选择用哪种

目前的你说的情况都是支持的，只是使用方式没有完全罗列。

唯一的问题就是 不带背景的时候 高度问题

**Comment by mumiao** [comment]
示例在完善一下，灰灰这几个例子还是蛮全的 @LuckyFBB

**Comment by mumiao** [comment]
closed: https://github.com/DTStack/dt-react-component/pull/251
