### ISSUE TITLE
StatusTag 组件

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/dt-react-component#265]
建议优化成不能换行
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/34759874/205235172-31b61ba8-9987-42f3-a703-e733090b184d.png">

ts/feat_5.3.2_all 

metaDataSync 元数据同步

**Comment by mumiao** [comment]
@LuckyFBB 这个看有木有个deadline，这个plan 跟着其他issues一起发v3.0.6版本

**Comment by mumiao** [comment]
doned with @LuckyFBB , Thanks PR
