### ISSUE TITLE
BlockHeader 增加下边距的配置

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/dt-react-component#280]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/38368040/209784988-0bbeeefd-13d8-4ac2-bebc-9461090103f3.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/38368040/209785115-39f0edb8-534e-4709-a20f-1ab56a0e8588.png">

发现 BlockHeader 在使用的时候，经常会带有 bottom: 16 的边距。

可以增加一个配置项给 BlockHeader 添加下边距。目前资产里面都是对样式的重写，觉得使用不友好。

**Comment by LuckyFBB** [comment]
开个 hasBottom(boolean) 的口子给大家，默认为false，不影响大家之前的使用，true的时候默认为16。。
再接受 spaceBottom 配置，处理 bottom 非16的情况。。

**Comment by liuxy0551** [comment]
done
