### ISSUE TITLE
资产使用 ModalWithForm ts 报错

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/dt-react-component#282]
![image](https://user-images.githubusercontent.com/38368040/211248865-a148bec8-9d3d-4ff2-b348-e92216b0692a.png)

**Comment by mumiao** [comment]
![image](https://user-images.githubusercontent.com/22880945/211310699-d4d1986f-11b3-4d2e-b349-2125da47d142.png)
这个类型之前定义的有问题，**React.ReactNode**包含了**string**类型，顺手改了好了

**Comment by mumiao** [comment]
done with #283
