### ISSUE TITLE
dumi迁移后antd样式丢失

### ISSUE THREAD

**Issue by JackWang032** [DTStack/dt-react-component#299]
- Table与其他部分antd组件样式会丢失

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/64318393/230892459-40cf5344-2f51-4e02-b6fe-c8e81923b26e.png">

**Comment by JackWang032** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/64318393/230892818-42236b93-1037-4f87-8ba4-eb8f06f1fe99.png">
可能是这块配置有点小小的问题

**Comment by mortalYoung** [comment]
好 我看看

**Comment by mortalYoung** [comment]
参考一下这个解决方案能不能解决：https://github.com/umijs/dumi/issues/1541#issuecomment-1467232077
