### ISSUE TITLE
EllipsisText 父级元素改变宽度，不会触发重新计算

### ISSUE THREAD

**Issue by Zaoei** [DTStack/dt-react-component#349]
https://github.com/DTStack/dt-react-component/assets/46592356/7d6ece43-6ba4-4a5c-956b-a38fc410cb0d

在进行数据切换时，可能由少数据变成多数据而出现滚动条改变的 dom 的宽度。

目前只监听宽口 Resize 事件，上面的情况触发不了 Resize 事件，导致 EllipsisText 展示异常。

**Comment by Zaoei** [comment]
- 解决一：用户在使用时固定元素的宽度（已支持）。
- 解决二：支持监听父元素大小的变化（待实现）

**Comment by mumiao** [comment]
#351
