### ISSUE TITLE
feature: table 的 column 支持 tooltip 属性

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/dt-react-component#352]
期望通过如下方式快速设置 tooltip

before:
```jsx
export default () => {
    return (<Table columns={[{
        key: 'name',
        dataIndex: 'name',
        title: (
           <Space>
                  name
             <Tooltip title="xxxxxx">
                 <QuestionCircleOutlined style={{ color: '#B1B4C5', fontSize: 14, verticalAlign: 'middle' }} />
             </Tooltip>
         </Space>
        )
    }]} />)
}
```

after
```jsx
export default () => {
    return (<Table columns={[{
        key: 'name',
        dataIndex: 'name',
        title: "name",
        tooltip: 'xxxxx'
    }]} />)
}
```

**Comment by mumiao** [comment]
> 期望通过如下方式快速设置 tooltip
> 
> before:
> 
> ```js
> export default () => {
>     return (<Table columns={[{
>         key: 'name',
>         dataIndex: 'name',
>         title: (
>            <Space>
>                   name
>              <Tooltip title="xxxxxx">
>                  <QuestionCircleOutlined style={{ color: '#B1B4C5', fontSize: 14, verticalAlign: 'middle' }} />
>              </Tooltip>
>          </Space>
>         )
>     }]} />)
> }
> ```
> 
> after
> 
> ```js
> export default () => {
>     return (<Table columns={[{
>         key: 'name',
>         dataIndex: 'name',
>         title: "name",
>         tooltip: 'xxxxx'
>     }]} />)
> }
> ```

可以的

**Comment by mumiao** [comment]
这个 @JackWang032 支持一下

**Comment by mortalYoung** [comment]
可能是我没表达清楚，我不是想要 Form.Table 支持，我想表达的是 Table 支持 0.0

**Comment by mumiao** [comment]
#356
