### ISSUE TITLE
查一下RC的utils

### ISSUE THREAD

**Issue by mumiao** [DTStack/dt-react-component#379]
**![image](https://github.com/DTStack/dt-react-component/assets/22880945/149c79ea-29fb-4b8f-9f46-0dc17eb5cd82)**
check一下 RC的工具包，看是不是和`dt-utils` 高度雷同，尤其cookie相关的utils方法，需要check一下和`dt-utils` 工具方法差异，以免带来bug，如果一模一样，可以废弃了。直接从 `dt-utils` 里面拉取

**Comment by JackWang032** [comment]
对比后 除了filterAttrByArrays方法，其他都可以直接使用dt-utils的

**Comment by JackWang032** [comment]
todo

**Comment by mumiao** [comment]
done
