### ISSUE TITLE
FilterRules Component present a complete and/or comprehensive demo

### ISSUE THREAD

**Issue by mumiao** [DTStack/dt-react-component#414]
**前**
![image](https://github.com/DTStack/dt-react-component/assets/22880945/4a09b622-d706-4598-96f2-7818e39b7599)
**后**
![image](https://github.com/DTStack/dt-react-component/assets/22880945/e3e2aa8b-b98e-4d92-ade5-edd31eac69a8)

**Comment by LuckyFBB** [comment]
done
