### ISSUE TITLE
[bug] slidePane 的 header 不应该滚动

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/dt-react-component#421]
# actual
![2023-11-30 15-32-16 2023-11-30 15_32_31](https://github.com/DTStack/dt-react-component/assets/18719701/dc7cf973-f3d4-4c70-b833-3d1383871979)

# Expect
![2023-11-30 15-33-04 2023-11-30 15_33_15](https://github.com/DTStack/dt-react-component/assets/18719701/73b755f4-46f1-4595-a324-8d1e51728b12)

**Comment by LuckyFBB** [comment]
done
