### ISSUE TITLE
fix style in component chromeDownload

### ISSUE THREAD

**Issue by haiminovo** [DTStack/dt-react-component#429]

**Comment by haiminovo** [comment]
before
![D22DA02C-1A55-4AD7-AD7B-6156536EA58D](https://github.com/DTStack/dt-react-component/assets/85284863/02f74831-c129-4acc-8796-f2724f032d56)
after
![image](https://github.com/DTStack/dt-react-component/assets/85284863/347af1f1-0113-4c9e-bf1f-b0e1e765f9d0)

**Comment by LuckyFBB** [comment]
done
