### ISSUE TITLE
5.1.0什么时候发布，版本停留在4.3.0，无法使用FilterRules

### ISSUE THREAD

**Issue by xpqxpxp** [DTStack/dt-react-component#456]

**Comment by LuckyFBB** [comment]
对应的 5.1.0 的 tag 已经有了，暂时还未发布到 npm 上
目前版本有些问题，会尽快解决发布对应的 npm 包。

**Comment by xpqxpxp** [comment]
filterRules有问题么？

**Comment by mumiao** [comment]
> filterRules有问题么？

filterRules已经完善掉，我们目前v5.0还不打算release，要发也是beta版本，如果着急使用的话可以先fork过去用，到时候再迁移，基本不会有大的变动
