### ISSUE TITLE
tag支持10px字体的svg

### ISSUE THREAD

**Issue by KinyooZ** [DTStack/dt-react-component#466]

**Comment by liuxy0551** [comment]
@LuckyFBB  设计师要求字体为 10px，贝儿调研可以通过 svg 实现，4.x 的 TinyTag 的 font-size 似乎也不满足
<img width="2279" alt="image" src="https://github.com/user-attachments/assets/e324064f-8fed-45ee-bef4-b8de482cbfd2">
