### ISSUE TITLE
[Bug]: useCookieListener 的 handler 存在闭包调用，导致无法拿到最新数据

### ISSUE THREAD

**Issue by jin-sir** [DTStack/dt-react-component#495]
### 组件

cookie

### 版本

5.x

### 期望的结果

useEffect 的定时器中 `compareValue->handler()` 调用的 handler 是最新的。

### 实际的结果

![image](https://github.com/user-attachments/assets/b5391632-0168-42b2-bdbb-3ba829f049b3)
![image](https://github.com/user-attachments/assets/2b7155eb-2165-4664-8c6d-d5b7b5db05c1)
使用 useEffect 开启定时器，在定时器中使用外部的`compareValue`方法，存在闭包问题，导致 `compareValue` 一直是最开始的，而`compareValue`中又调用了外部的`handler`，`handler`被`compareValue`闭包了，导致`handler`中的所有数据都是最开始的状态，不是最新数据。

**Comment by LuckyFBB** [comment]
done
