### ISSUE TITLE
ellipisisText

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/dt-react-component#5]
1. ellipsisText 用来文本溢出打点展示，但这个组件生成的元素是块级元素，会独占一行,文本应使用行内元素包裹
2. 使用ellipsisText后展示的文本会纵向偏移

**Comment by zhangtengjin** [comment]
由于源代码中使用了 overflow: hidden 属性，导致默认的 baseline 被强制修改，致其相邻的兄弟元素出现下移现象。下版本我们会优先掉这个问题
